- name: Upgrade hosts packages
  hosts: all
  tasks:
    - name: Update packages
      become: yes
      apt: 
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    - name: Upgrade packages
      become: yes
      apt: 
        upgrade: dist
        force_apt_get: yes
        autoremove: yes
        autoclean: yes
    - name: Check if needs to reboot
      become: yes
      register: reboot_required_file
      stat: 
        path: /var/run/reboot-required
        get_md5: no
